version: '3'
services:
    express:
        build: 
            context: . 
            dockerfile: Dockerfile
        image: globechain_image:local
        container_name: globechain_container01
        restart: always
        ports:
            - "8080:8080"
        volumes:
            - ./:/globechain
            - /globechain/node_modules